// Independent vectors generated with Python bz2/lzma; no Adobe payloads.
namespace AdobeDownloader.Core.Tests;
internal static class PatchFixtures
{
    internal static byte[] Simple => Convert.FromBase64String("QlNESUZGNDAqAAAAAAAAACUAAAAAAAAABAAAAAAAAABCWmg5MUFZJlNZ0BSaKQAABMAAaAggADDNNBk/UglZPF3JFOFCQ0BSaKRCWmg5MUFZJlNZTFqfSAAAAEAAYAAgACEAgoxdyRThQkExan0gQlpoOTFBWSZTWS0V6xwAAAAQACAAIAAhGEaC7kinChIFor1jgA==");
    internal static byte[] Padded => Convert.FromBase64String("QlNESUZGNDAqAAAAAAAAACUAAAAAAAAABAAAAAAAAABCWmg5MUFZJlNZ0BSaKQAABMAAaAggADDNNBk/UglZPF3JFOFCQ0BSaKRCWmg5MUFZJlNZuTfo5AAAAUAAYAAgACEAgoMXckU4UJC5N+jkQlpoOTFBWSZTWfKHIkEAAALQAEAAIAAgACEAgpMXckU4UJDyhyJB");
    internal static byte[] BadPadding => Convert.FromBase64String("QlNESUZGNDAqAAAAAAAAACYAAAAAAAAABAAAAAAAAABCWmg5MUFZJlNZ0BSaKQAABMAAaAggADDNNBk/UglZPF3JFOFCQ0BSaKRCWmg5MUFZJlNZ42DYNgAAAEAAcAAgACGYGYTMLuSKcKEhxsGwbEJaaDkxQVkmU1ktFescAAAAEAAgACAAIRhGgu5IpwoSBaK9Y4A=");
    internal static byte[] ExcessPadding => Convert.FromBase64String("QlNESUZGNDAqAAAAAAAAACUAAAAAAAAABAAAAAAAAABCWmg5MUFZJlNZ0BSaKQAABMAAaAggADDNNBk/UglZPF3JFOFCQ0BSaKRCWmg5MUFZJlNZGejZOgAAAcAAYAAgACEAgpMXckU4UJAZ6Nk6QlpoOTFBWSZTWS0V6xwAAAAQACAAIAAhGEaC7kinChIFor1jgA==");
    internal static byte[] NegativeSeek => Convert.FromBase64String("QlNESUZGNDAxAAAAAAAAACUAAAAAAAAABAAAAAAAAABCWmg5MUFZJlNZTongCQAABmBAeAgIAEAAIAAxDADR6TIDeJSF1XxdyRThQkE6J4AkQlpoOTFBWSZTWTj7IoQAAAJAAEAAIAAhGEawu5IpwoSBx9kUIEJaaDkXckU4UJAAAAAA");
    internal static byte[] BeyondTarget => Convert.FromBase64String("QlNESUZGNDApAAAAAAAAACUAAAAAAAAABAAAAAAAAABCWmg5MUFZJlNZDIN1CAAAAmAAQgAIACAAMMwM9QXOLuSKcKEgGQbqEEJaaDkxQVkmU1m470RjAAAAQABgACAAIQCCgxdyRThQkLjvRGNCWmg5F3JFOFCQAAAAAA==");
    internal static byte[] LzmaOld => Convert.FromBase64String("EAEAAmFiYwA=");
}
